"""initial migration

Revision ID: 13584015fc9c
Revises: 
Create Date: 2026-05-03 21:13:15.567088

"""
from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '13584015fc9c'
down_revision = None
branch_labels = None
depends_on = None

EMBEDDING_DIM = 384

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table('collection',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('topic',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('visualisation_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=EMBEDDING_DIM), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'slug')
    )
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.create_index('ix_topic_embedding', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
        batch_op.create_index('ix_topic_search_vector', ['search_vector'], unique=False, postgresql_using='gin')

    op.create_table('link',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('link_text', sa.String(), nullable=False),
    sa.Column('link_type', sa.Enum('website', 'dataset', 'api', name='linktype'), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # manually added as alembic doesn't know indexing trigger needed
    op.execute("""
        CREATE FUNCTION topic_search_vector_update() RETURNS trigger AS $$
        BEGIN
            NEW.search_vector :=
                setweight(to_tsvector('english', COALESCE(NEW.title, '')), 'A') ||
                setweight(to_tsvector('english', COALESCE(NEW.body, '')), 'B');
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    op.execute("""
        CREATE TRIGGER topic_search_vector_trigger
        BEFORE INSERT OR UPDATE OF title, body ON topic
        FOR EACH ROW EXECUTE FUNCTION topic_search_vector_update();
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS topic_search_vector_trigger ON topic")
    op.execute("DROP FUNCTION IF EXISTS topic_search_vector_update")
    op.drop_table('link')
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_index('ix_topic_search_vector', postgresql_using='gin')
        batch_op.drop_index('ix_topic_embedding', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})

    op.drop_table('topic')
    op.drop_table('collection')
    op.execute("DROP TYPE IF EXISTS linktype")
    # ### end Alembic commands ###
